# -*- coding: utf-8 -*-
"""Worksheet2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSJiiqSVEKqHkAmCkA3I89c5lsuML_co
"""

import pandas as pd

# ----------------------------
# Problem 1 – Data Read, Inspect
# ----------------------------

# 1. Load the dataset
bank = pd.read_csv("csv/bank.csv")
bank.head()

#2. Data Info Check
bank.info()

#(a) object dtype columns
bank = pd.read_csv("csv/bank.csv")

object_cols = bank.select_dtypes(include='object').columns
print("Object Columns:", object_cols.tolist())

#(b) unique values
for col in object_cols:
    print(f"\nUnique values in {col}:")
    print(bank[col].unique())

#(C)checking null in each column
print("\nNull values in each column:")
print(bank.isnull().sum())

#3. Drop object columns + save new CSV
bank = pd.read_csv("csv/bank.csv")
object_cols = bank.select_dtypes(include='object').columns
bank_numeric = bank.drop(columns=object_cols)
# Write to CSV
bank_numeric.to_csv("banknumericdata.csv", index=False)

#4. Read New CSV + Summary Statistics
bank_numeric2 = pd.read_csv("banknumericdata.csv")
bank_numeric2.describe()

#Problem 2 — Data Imputation (medical_student.csv)
#1. Load Dataset
import pandas as pd

medical_df = pd.read_csv("csv/medical_students.csv")
medical_df.head()

#2. Check DataFrame info
medical_df.info()

# Check for missing values
missing_summary = medical_df.isnull().sum()
print("Missing values per column:\n", missing_summary)

#3. Fill Missing Values
import pandas as pd

# Load the dataset
med = pd.read_csv("csv/medical_students.csv")

# Identify numeric columns
numeric_cols = med.select_dtypes(include=['float64', 'int64']).columns

# Fill missing values with median
for col in numeric_cols:
    if med[col].isnull().sum() > 0:
        med[col] = med[col].fillna(med[col].median())
        print(f"Filled missing values in numeric column '{col}' with median")

#Fill Categorical Columns with Mode
# Identify categorical columns
categorical_cols = med.select_dtypes(include=['object']).columns

# Fill missing values with mode
for col in categorical_cols:
    if med[col].isnull().sum() > 0:
        med[col] = med[col].fillna(med[col].mode()[0])
        print(f"Filled missing values in categorical column '{col}' with mode")

print("=== NULL VALUES AFTER IMPUTATION ===")
print(med.isnull().sum())

# Check how many duplicate rows exist
duplicate_count = med.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
med = med.drop_duplicates()

# Confirm new shape of the dataset
print("Shape after removing duplicates:", med.shape)

#3.2 Titanic Dataset — EDA
titanic = pd.read_csv("csv/titanic.csv")
titanic.head()

#Problem 1 — Subset + Fare Statistics
#Subset and fare
subset = titanic[['Name','Pclass','Sex','Age','Fare','Survived']]

# First Class only
first_class = subset[subset['Pclass'] == 1]

# Calculate stats
print("Mean Fare:", first_class['Fare'].mean())
print("Median Fare:", first_class['Fare'].median())
print("Min Fare:", first_class['Fare'].min())
print("Max Fare:", first_class['Fare'].max())

#Problem 2 — Null Values in Age
print("Null Age count:", first_class['Age'].isnull().sum())

# Drop null rows
first_class_clean = first_class.dropna(subset=['Age'])
first_class_clean.head()

#Problem 3
# One-hot encode 'Embarked'
embarked_encoded = pd.get_dummies(titanic['Embarked'], prefix='Embarked')

# Add to original DataFrame
titanic_encoded = pd.concat([titanic, embarked_encoded], axis=1)

# Drop original 'Embarked' column
titanic_encoded.drop(columns=['Embarked'], inplace=True)

# Preview result
print(titanic_encoded.head())

#Problem 4 — Survival by Embarked + Gender
import seaborn as sns
import matplotlib.pyplot as plt

# Survival rate by gender
survival_by_gender = titanic.groupby('Sex')['Survived'].mean()
print("Survival rate by gender:\n", survival_by_gender)

# Plot
sns.barplot(x=survival_by_gender.index, y=survival_by_gender.values)
plt.title("Survival Rate by Gender")
plt.ylabel("Survival Rate")
plt.xlabel("Gender")
plt.show()

#Problem 5 (Survival Rate by Embarkation Port
# Group by Embarked and Sex
survival_by_embarked = titanic.groupby(['Embarked', 'Sex'])['Survived'].mean().unstack()

# Plot
survival_by_embarked.plot(kind='bar')
plt.title("Survival Rate by Embarkation Port and Gender")
plt.ylabel("Survival Rate")
plt.xlabel("Embarkation Port")
plt.legend(title="Gender")
plt.show()

#Problem 6 (Optional): Survival by Age Group + Pclass
# Create age quantiles
titanic['AgeGroup'] = pd.qcut(titanic['Age'], 5)

# Group by AgeGroup and Pclass
survival_by_age_pclass = titanic.groupby(['AgeGroup', 'Pclass'])['Survived'].mean().unstack()

# Plot
survival_by_age_pclass.plot(kind='bar', figsize=(10,6))
plt.title("Survival Rate by Age Group and Passenger Class")
plt.ylabel("Survival Rate")
plt.xlabel("Age Group")
plt.legend(title="Pclass")
plt.show()

