# -*- coding: utf-8 -*-
"""Worksheet3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bY_SGfdECjnWxdAUSD7xct5_V2Wwgpoc
"""

# =======================================================================
#  Worksheet – 3 : Exploratory Data Analysis (Part – II)
#  COMPLETE SOLUTION CODE USING TITANIC DATASET
# =======================================================================

import pandas as pd
import numpy as np

# ------------------------------ Load dataset ----------------------------
df = pd.read_csv("Titanic-Dataset.csv")

print("\n=== Dataset Info ===")
print(df.info())

print("\n=== First 5 Rows ===")
print(df.head())

# =======================================================================
#  PROBLEM 1 – SORTING / COLUMN SELECTION
# =======================================================================

# 1. fare DataFrame (only Fare column)
fare = df[["Fare"]]
print("\n=== fare DataFrame ===")
print(fare.head())

# 2. class_age DataFrame (Pclass & Age)
class_age = df[["Pclass", "Age"]]
print("\n=== class_age DataFrame ===")
print(class_age.head())

# 3. survived_gender DataFrame (Survived & Sex)
survived_gender = df[["Survived", "Sex"]]
print("\n=== survived_gender DataFrame ===")
print(survived_gender.head())

# =======================================================================
#  PROBLEM 2 – SUBSETTING
# =======================================================================

# 1. Fare > 100
fare_gt_100 = df[df["Fare"] > 100]
print("\n=== Fare > 100 ===")
print(fare_gt_100.head())

# 2. Passengers in First Class
first_class = df[df["Pclass"] == 1]
print("\n=== Pclass == 1 ===")
print(first_class.head())

# 3. Female passengers under 18
female_under_18 = df[(df["Age"] < 18) & (df["Sex"] == "female")]
print("\n=== Female under 18 ===")
print(female_under_18.head())

# ---- Subsetting by categorical variables ----

# 1. Embarked = C or S
embarked_c_or_s = df[df["Embarked"].isin(["C", "S"])]
print("\n=== Embarked C or S ===")
print(embarked_c_or_s.head())

# 2. First & Second class passengers
first_second_class = df[df["Pclass"].isin([1, 2])]
print("\n=== Pclass in [1, 2] ===")
print(first_second_class.head())

# ======================================================================
# 3.2 – EDA PRACTICE EXERCISE
# ======================================================================
df2 = df.copy()

# Fill Missing Age
df2["Age"] = df2["Age"].fillna(df2["Age"].median())

# 1. Add new column: fare_per_year = Fare / Age
df2["fare_per_year"] = df2["Fare"] / df2["Age"]

print("\n=========== Practice 3.2 (1) – Added fare_per_year column ===========")
print(df2[["Name", "Fare", "Age", "fare_per_year"]].head())


# 2. Subset: fare_per_year > 5
high_fare_age = df2[df2["fare_per_year"] > 5]

# 3. Sort descending
high_fare_age_sorted = high_fare_age.sort_values(by="fare_per_year", ascending=False)

# 4. Select Name + fare_per_year
result1 = high_fare_age_sorted[["Name", "fare_per_year"]]

print("\n=========== Practice 3.2 (2–4) – fare_per_year > 5 Sorted ===========")
print(result1.head(20))

# ── BONUS QUESTION: Which adult male paid highest fare relative to class?

df2["fare_per_class"] = df2["Fare"] / df2["Pclass"]

adult_males = df2[(df2["Sex"] == "male") & (df2["Age"] >= 18)]
adult_sorted = adult_males.sort_values(by="fare_per_class", ascending=False)

print("\n=========== Practice 3.2 (Bonus) – Adult Male Highest fare/class ===========")
print(adult_sorted[["Name", "Age", "fare_per_class"]].head(1))

# ======================================================================
#  3.3 – GROUP-BY PRACTICE EXERCISE
# ======================================================================

# 1. Total fare of all passengers
total_fare = df["Fare"].sum()
print("Total Fare Paid =", total_fare)

# 2. Total fare for First Class (Pclass = 1)
fare_first = df[df["Pclass"] == 1]["Fare"].sum()
print("First Class Fare Total =", fare_first)

# 3. Total fare for Second Class (Pclass = 2)
fare_second = df[df["Pclass"] == 2]["Fare"].sum()
print("Second Class Fare Total =", fare_second)

# 4. Total fare for Third Class (Pclass = 3)
fare_third = df[df["Pclass"] == 3]["Fare"].sum()
print("Third Class Fare Total =", fare_third)
# Combine into a list
fare_list = [fare_first, fare_second, fare_third]
print("\nFare Totals List =", fare_list)

# 5. Calculate proportion (percentage)
fare_percentage = [(x / total_fare) * 100 for x in fare_list]

print("\nPercentage of Fare Revenue by Class:")
print(f"First Class  : {fare_percentage[0]:.2f}%")
print(f"Second Class : {fare_percentage[1]:.2f}%")
print(f"Third Class  : {fare_percentage[2]:.2f}%")

# ----------------- PART B: Age Group percentages -----------------

df_age = df.copy()

# Fill missing ages with median
df_age["Age"] = df_age["Age"].fillna(df_age["Age"].median())

# 1. Create age_group column
def get_age_group(age):
    if age < 18:
        return "child"
    elif age <= 64:
        return "adult"
    else:
        return "senior"

df_age["age_group"] = df_age["Age"].apply(get_age_group)

# 2. Total passengers
total_passengers = len(df_age)

# 3. Count passengers per age group
age_counts = df_age["age_group"].value_counts()

# 4. Proportion = count / total
age_prop = (age_counts / total_passengers) * 100

# 5. Display percentages
print("\nPercentage of Passengers by Age Group:")
print(age_prop)

