# -*- coding: utf-8 -*-
"""workshop1_DiptiGiri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckq7QReFFCAUnLWp9zabIBEGaSRhL7OR
"""

import numpy as np

# 1. Empty array 2x2
empty_arr = np.empty((2,2))
print("1. Empty Array:\n", empty_arr)

# 2. Ones array 4x2
ones_arr = np.ones((4,2))
print("\n2. Ones Array:\n", ones_arr)

# 3. Array full of given value
full_arr = np.full((3,3), 7)   # 7 is fill value
print("\n3. Full Array:\n", full_arr)

# 4. Zeros like another array
ref = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(ref)
print("\n4. Zeros Like:\n", zeros_like_arr)

# 5. Ones like another array
ones_like_arr = np.ones_like(ref)
print("\n5. Ones Like:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
np_arr = np.array(new_list)
print("\n6. Converted Array:\n", np_arr)

#Task 2
import numpy as np

# 1. Array from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. 10 to 49:\n", arr_10_49)

# 2. 3x3 matrix from 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)
print("\n2. 3x3 Matrix:\n", matrix_3x3)

# 3. Identity matrix 3x3
identity_3 = np.eye(3)
print("\n3. Identity Matrix:\n", identity_3)

# 4. Random array of 30 – mean
rand_30 = np.random.random(30)
print("\n4. Mean:", rand_30.mean())

# 5. 10x10 random min and max
rand_10x10 = np.random.random((10,10))
print("\n5. Min:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Replaced Array:\n", zero_arr)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
rev_arr = arr[::-1]
print("\n7. Reversed:\n", rev_arr)

# 8. 2D array with border 1 and inside 0
border_arr = np.ones((5,5))
border_arr[1:-1,1:-1] = 0
print("\n8. Border Array:\n", border_arr)

# 9. Checkerboard pattern 8x8
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n9. Checkerboard Pattern:\n", checker)

#Task 3
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("1. Add:\n", x + y)

# 2. Subtract
print("\n2. Subtract:\n", x - y)

# 3. Multiply with integer
print("\n3. Multiply with 3:\n", x * 3)

# 4. Square of each element
print("\n4. Square:\n", x**2)

# 5. Dot products
print("\n5. Dot(v,w):", np.dot(v,w))
print("Dot(x,v):\n", x.dot(v))
print("Dot(x,y):\n", x.dot(y))

# 6. Concatenate rows & columns
print("\n6. Concat x & y (row):\n", np.concatenate((x,y), axis=0))
print("Concat v & w (column):\n", np.vstack((v,w)))

# 7. Concatenate x and v → error explanation
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("\n7. ERROR because shapes don't match:")
    print(e)

#task 4
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A A^-1 = I
A_inv = np.linalg.inv(A)
print("1. A * A^-1:\n", A.dot(A_inv))

# 2. AB != BA
print("\n2. AB:\n", A.dot(B))
print("   BA:\n", B.dot(A))

# 3. (AB)^T = B^T A^T
AB = A.dot(B)
LHS = AB.T
RHS = B.T.dot(A.T)
print("\n3. LHS:\n", LHS)
print("   RHS:\n", RHS)

# Solve Linear System using Matrix form
M = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b = np.array([-1,-3,9])

solution = np.linalg.solve(M,b)
print("\nSolution (Solve):\n", solution)

# Solve using inverse
M_inv = np.linalg.inv(M)
solution2 = M_inv.dot(b)
print("\nSolution (Inverse Method):\n", solution2)

#task 5
import numpy as np
import time

# LIST vs NUMPY speed test
N = 1_000_000
list1 = list(range(N))
list2 = list(range(N))

arr1 = np.arange(N)
arr2 = np.arange(N)

# 1. Addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(N)]
print("List Add Time:", time.time() - start)

start = time.time()
np_add = arr1 + arr2
print("Numpy Add Time:", time.time() - start)

# 2. Multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(N)]
print("\nList Mul Time:", time.time() - start)

start = time.time()
np_mul = arr1 * arr2
print("Numpy Mul Time:", time.time() - start)

# 3. Dot Product
start = time.time()
dot_list = sum([list1[i]*list2[i] for i in range(N)])
print("\nList Dot Time:", time.time() - start)

start = time.time()
dot_np = np.dot(arr1, arr2)
print("Numpy Dot Time:", time.time() - start)

# 4. Matrix Multiplication 1000x1000
A = np.random.random((1000,1000)).tolist()
B = np.random.random((1000,1000)).tolist()

start = time.time()
C = [[sum(a*b for a,b in zip(row,col)) for col in zip(*B)] for row in A]
print("\nList Matrix Mul Time:", time.time() - start)

A_np = np.array(A)
B_np = np.array(B)
start = time.time()
C_np = A_np.dot(B_np)
print("Numpy Matrix Mul Time:", time.time() - start)

